
var TB_BASE = 'https://threeblockly.github.io';
//var TB_BASE = 'http://localhost:8080/threeblockly.github.io';

WS_STATES = {

	'intro' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"|M3|.UhtIA~RlaMa:PFv","x":38,"y":39,"inputs":{"geometry":{"block":{"type":"create_sphere","id":"T[4d)_dk.B0mRpd!zpdC","fields":{"radius":2}}},"material":{"block":{"type":"create_material","id":"noM%J3~jv@nyDab]!KQx","fields":{"color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',
	
	'seclipse' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"(@Rj3kq9Ibu8m=wrJ`I@","x":52,"y":-190,"fields":{"pos_x":-15,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":",{tOWw0J?}[k/SQjeik3","fields":{"radius":10}}},"material":{"block":{"type":"create_material","id":"Rq5^V`%z8pn2a3k,Xtj]","fields":{"type":"basic","color":"#ffcc00","image":""}}}}},{"type":"create_mesh","id":"##tP8_.BZe$X+:QsH@BP","x":47,"y":44,"fields":{"pos_x":0,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":"YPOk5[yx93!*ljh$J(.r","fields":{"radius":0.25}}},"material":{"block":{"type":"create_material","id":"5k0goCYM@2KgIgC,E,I-","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/moon.jpg"}}}}},{"type":"create_mesh","id":"r=./sg2XmMTYto7}3A^g","x":54,"y":281,"fields":{"pos_x":3,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":"o,^5fViX(grNo`,/2v!5","fields":{"radius":1}}},"material":{"block":{"type":"create_material","id":"1i(iZJyTFc$JW?uPS~#l","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',
	
	'leclipse' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"(@Rj3kq9Ibu8m=wrJ`I@","x":52,"y":-190,"fields":{"pos_x":-15,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":",{tOWw0J?}[k/SQjeik3","fields":{"radius":10}}},"material":{"block":{"type":"create_material","id":"Rq5^V`%z8pn2a3k,Xtj]","fields":{"type":"basic","color":"#ffcc00","image":""}}}}},{"type":"create_mesh","id":"##tP8_.BZe$X+:QsH@BP","x":47,"y":44,"fields":{"pos_x":3,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":"YPOk5[yx93!*ljh$J(.r","fields":{"radius":0.25}}},"material":{"block":{"type":"create_material","id":"5k0goCYM@2KgIgC,E,I-","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/moon.jpg"}}}}},{"type":"create_mesh","id":"r=./sg2XmMTYto7}3A^g","x":54,"y":281,"fields":{"pos_x":0,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":"o,^5fViX(grNo`,/2v!5","fields":{"radius":1}}},"material":{"block":{"type":"create_material","id":"1i(iZJyTFc$JW?uPS~#l","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',

};