
var TB_BASE = 'https://threeblockly.github.io';
//var TB_BASE = 'http://localhost:8080/TI/threeblockly.github.io';

WS_STATES = {

	'intro' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"|M3|.UhtIA~RlaMa:PFv","x":38,"y":39,"inputs":{"geometry":{"block":{"type":"create_sphere","id":"T[4d)_dk.B0mRpd!zpdC","fields":{"radius":2}}},"material":{"block":{"type":"create_mesh_material","id":"noM%J3~jv@nyDab]!KQx","fields":{"color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',

	'helloworld' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"Hn=Nn7jJTeG~Ut?TJCdn","x":49,"y":29,"fields":{"pos_x":-1.5,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_text","id":"`s)]=~.p#TJ(m/jMTmW0","fields":{"text":"Hello"}}},"material":{"block":{"type":"create_mesh_material","id":"ypxNXJQHtVj7!e+vknbs","fields":{"type":"phong","color":"#ffcc00","image":""}}}}},{"type":"create_mesh","id":";W]dV/@,zBfyfzD(i/gb","x":62,"y":230,"fields":{"pos_x":0,"pos_y":-0.05,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_cube","id":"/H(I5)r{j0l|6o#h/56Z","fields":{"width":4,"height":0.1,"depth":1}}}}},{"type":"create_mesh","id":"wiantx9UJSl-S%6FSNch","x":51,"y":452,"fields":{"pos_x":0,"pos_y":-1,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":"].mBAhNWd2|f:SvvPjXn","fields":{"radius":1}}},"material":{"block":{"type":"create_mesh_material","id":"#cUTyF,?Z*Vd8dQ@{Iq;","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',

	'seclipse' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"(@Rj3kq9Ibu8m=wrJ`I@","x":52,"y":-190,"fields":{"pos_x":-15,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere", "collapsed":true, "id":",{tOWw0J?}[k/SQjeik3","fields":{"radius":10}}},"material":{"block":{"type":"create_mesh_material", "collapsed":true, "id":"Rq5^V`%z8pn2a3k,Xtj]","fields":{"type":"basic","color":"#ffcc00","image":""}}}}},{"type":"create_mesh","id":"##tP8_.BZe$X+:QsH@BP","x":47,"y":44,"fields":{"pos_x":0,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere", "collapsed":true, "id":"YPOk5[yx93!*ljh$J(.r","fields":{"radius":0.25}}},"material":{"block":{"type":"create_mesh_material", "collapsed":true, "id":"5k0goCYM@2KgIgC,E,I-","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/moon.jpg"}}}}},{"type":"create_mesh","id":"r=./sg2XmMTYto7}3A^g","x":54,"y":281,"fields":{"pos_x":3,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere", "collapsed":true, "id":"o,^5fViX(grNo`,/2v!5","fields":{"radius":1}}},"material":{"block":{"type":"create_mesh_material", "collapsed":true, "id":"1i(iZJyTFc$JW?uPS~#l","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',
	
	'leclipse' : '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_mesh","id":"(@Rj3kq9Ibu8m=wrJ`I@","x":52,"y":-190,"fields":{"pos_x":-15,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","collapsed":true, "id":",{tOWw0J?}[k/SQjeik3","fields":{"radius":10}}},"material":{"block":{"type":"create_mesh_material","collapsed":true,"id":"Rq5^V`%z8pn2a3k,Xtj]","fields":{"type":"basic","color":"#ffcc00","image":""}}}}},{"type":"create_mesh","id":"##tP8_.BZe$X+:QsH@BP","x":47,"y":44,"fields":{"pos_x":3,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere", "collapsed":true, "id":"YPOk5[yx93!*ljh$J(.r","fields":{"radius":0.25}}},"material":{"block":{"type":"create_mesh_material", "collapsed":true, "id":"5k0goCYM@2KgIgC,E,I-","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/moon.jpg"}}}}},{"type":"create_mesh","id":"r=./sg2XmMTYto7}3A^g","x":54,"y":281,"fields":{"pos_x":0,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere", "collapsed":true, "id":"o,^5fViX(grNo`,/2v!5","fields":{"radius":1}}},"material":{"block":{"type":"create_mesh_material", "collapsed":true, "id":"1i(iZJyTFc$JW?uPS~#l","fields":{"type":"basic","color":"#ffffff","image":"'+TB_BASE+'/img/eg/world.jpg"}}}}}]}}',
	
	'simple-csg': '{"blocks":{"languageVersion":0,"blocks":[{"type":"create_csg","id":"m^B]/o|uozeZnj{|]7:F","x":52,"y":177,"fields":{"operation":"SUBTRACTION"},"inputs":{"brush1":{"block":{"type":"create_brush","id":"B1h8~c(@i+X0pXfxnSW,","inline":true,"inputs":{"geometry":{"block":{"type":"create_cube","id":"URJjp0]EQf/2?/U%=(v.","inline":true,"fields":{"width":1.5,"height":1.5,"depth":1.5}}},"material":{"block":{"type":"create_mesh_material","id":"rf$Yy`_Rd9POQSRbz@lQ","inline":true,"fields":{"type":"standard","color":"#3366ff","image":""}}}}}},"brush2":{"block":{"type":"create_brush","id":"C0iliuLNP}d;+)oItu,C","inline":true,"inputs":{"geometry":{"block":{"type":"create_sphere","id":"w6u)w^PacBg;_*Gqhh7[","inline":true,"fields":{"radius":1}}},"material":{"block":{"type":"create_mesh_material","id":"P}hd/]=uqH/#6|fv8IJA","inline":true,"fields":{"type":"basic","color":"#33cc00","image":""}}}}}}}},{"type":"adjust_scene","id":"KV}SKz_2w7wbHh1TBm0_","x":55,"y":6,"inline":true,"fields":{"color":"#ffffff"}},{"type":"adjust_camera","id":"`YBL3Q6Fq|0b%tb07u=h","x":53,"y":40,"inline":true,"fields":{"pos_x":0,"pos_y":1,"pos_z":1}},{"type":"create_mesh","id":":$.qrsji*@^BKw{5!JT^","x":52,"y":298,"fields":{"pos_x":0,"pos_y":0,"pos_z":0,"rot_x":0,"rot_y":0,"rot_z":0},"inputs":{"geometry":{"block":{"type":"create_sphere","id":"HF*:!FO{09daEWfrLywG","inline":true,"fields":{"radius":0.75}}},"material":{"block":{"type":"create_mesh_material","id":"tkz=m8yHj*MR%t3krLIi","inline":true,"fields":{"type":"standard","color":"#ff0000","image":""}}}}},{"type":"adjust_lights","id":"hP4Y[|hC~P%p7_C$y_g4","x":54,"y":80,"fields":{"ambColor":"#ffffff","ambIntense":2,"dirColor":"#ffffff","dirIntense":2,"pos_x":1,"pos_y":5,"pos_z":1}}]}}'

};